import { ICourseLanguageSelection, ILanguage } from '../shared/interface';

export const LANGUAGE_CODES: ILanguage[] = [
  { id: 'af', icon: '🇿🇦', title: 'Afrikaans' },
  { id: 'ar', icon: '🇸🇦', title: 'Arabic' },
  { id: 'bg', icon: '🇧🇬', title: 'Bulgarian' },
  { id: 'bn', icon: '🇧🇩', title: 'Bengali' },
  { id: 'ca', icon: '🇪🇸', title: 'Catalan' },
  { id: 'cs', icon: '🇨🇿', title: 'Czech' },
  { id: 'da', icon: '🇩🇰', title: 'Danish' },
  { id: 'de', icon: '🇩🇪', title: 'German' },
  { id: 'el', icon: '🇬🇷', title: 'Greek' },
  { id: 'en', icon: '🇬🇧', title: 'English' },
  { id: 'es', icon: '🇪🇸', title: 'Spanish' },
  { id: 'et', icon: '🇪🇪', title: 'Estonian' },
  { id: 'fa', icon: '🇮🇷', title: 'Persian' },
  { id: 'fi', icon: '🇫🇮', title: 'Finnish' },
  { id: 'fr', icon: '🇫🇷', title: 'French' },
  { id: 'he', icon: '🇮🇱', title: 'Hebrew' },
  { id: 'hi', icon: '🇮🇳', title: 'Hindi' },
  { id: 'hr', icon: '🇭🇷', title: 'Croatian' },
  { id: 'hu', icon: '🇭🇺', title: 'Hungarian' },
  { id: 'id', icon: '🇮🇩', title: 'Indonesian' },
  { id: 'it', icon: '🇮🇹', title: 'Italian' },
  { id: 'ja', icon: '🇯🇵', title: 'Japanese' },
  { id: 'ko', icon: '🇰🇷', title: 'Korean' },
  { id: 'lt', icon: '🇱🇹', title: 'Lithuanian' },
  { id: 'lv', icon: '🇱🇻', title: 'Latvian' },
  { id: 'ms', icon: '🇲🇾', title: 'Malay' },
  { id: 'nb', icon: '🇳🇴', title: 'Norwegian Bokmål' },
  { id: 'nl', icon: '🇳🇱', title: 'Dutch' },
  { id: 'pl', icon: '🇵🇱', title: 'Polish' },
  { id: 'pt', icon: '🇵🇹', title: 'Portuguese' },
  { id: 'ro', icon: '🇷🇴', title: 'Romanian' },
  { id: 'ru', icon: '🇷🇺', title: 'Russian' },
  { id: 'sk', icon: '🇸🇰', title: 'Slovak' },
  { id: 'sl', icon: '🇸🇮', title: 'Slovenian' },
  { id: 'sr', icon: '🇷🇸', title: 'Serbian' },
  { id: 'sv', icon: '🇸🇪', title: 'Swedish' },
  { id: 'th', icon: '🇹🇭', title: 'Thai' },
  { id: 'tr', icon: '🇹🇷', title: 'Turkish' },
  { id: 'uk', icon: '🇺🇦', title: 'Ukrainian' },
  { id: 'ur', icon: '🇵🇰', title: 'Urdu' },
  { id: 'vi', icon: '🇻🇳', title: 'Vietnamese' },
  { id: 'zh', icon: '🇨🇳', title: 'Chinese' },
];

export const COURSE_LANGUAGE_SELECTIONS: ICourseLanguageSelection[] = [
  { id: 'firstLanguage', title: 'First Language' },
  { id: 'secondLanguage', title: 'Second Language' },
  { id: 'thirdLanguage', title: 'Third Language' },
];
